services:
  binventory:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FRONTEND_URL=http://localhost:8000  # Updated to use the same URL
      - STATIC_FILES_DIR=/app/static
    volumes:
      - ./binventory.db:/app/binventory.db  # Persist database
