version: '3'

services:
  binventory:
    build: .
    container_name: binventory
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - binventory-data:/app/data
    environment:
      - TZ=UTC

volumes:
  binventory-data:
    name: binventory-data